# app/db/project_repository.py

from sqlalchemy.orm import Session
from typing import List, Optional
from app.db.models import Project, ProjectFile # Import the SQLAlchemy models

class ProjectRepository:
    """
    Encapsulates all database access logic for the Project and related tables.
    Adheres to the Repository Pattern, ensuring the Service Layer is unaware of
    database specifics (like SQLAlchemy, ORMs, or SQL).
    """
    
    def __init__(self, db_session: Session):
        """
        The DB session is injected into the repository instance.
        """
        self.db = db_session
        
    def create_project_and_files(self, project: Project, files: List[ProjectFile]) -> Project:
        """
        Persists the new Project and all associated ProjectFile records 
        in a single, atomic transaction.
        
        Args:
            project: The new Project model instance.
            files: A list of new ProjectFile model instances.
            
        Returns:
            The committed Project instance.
        """
        try:
            # 1. Add the main project record
            self.db.add(project)
            
            # 2. Add all file records
            for file in files:
                self.db.add(file)
            
            # 3. Commit the transaction (atomicity guaranteed here)
            self.db.commit()
            
            # 4. Refresh the project to ensure we have any defaults generated by the DB
            self.db.refresh(project)
            
            return project
            
        except Exception as e:
            # CRITICAL: Rollback the entire transaction on failure
            self.db.rollback()
            # Re-raise the exception for the Service Layer to handle (e.g., clean up files)
            raise e
            
    # FUTURE METHODS (Just for context, not needed for Feature 1 POST)
    
    # def get_project_by_id(self, project_id: str) -> Optional[Project]:
    #     """Fetches a project by its ID."""
    #     return self.db.query(Project).filter(Project.project_id == project_id).first()
    
    # def update_project_state(self, project_id: str, current_phase: str, next_agent: str):
    #     """Updates the phase and next agent fields."""
    #     # ... implementation ...
    #     pass