"""Add institution and profession to User model

Revision ID: 9027eac4fdbc
Revises: eecbf3e700ea
Create Date: 2025-11-13 22:59:47.597302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9027eac4fdbc'
down_revision: Union[str, Sequence[str], None] = 'eecbf3e700ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institute', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('profession', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profession')
        batch_op.drop_column('institute')

    # ### end Alembic commands ###
